"""добавил таблицы: Permission и RolePermission для назначения действий и соотношения к ролям. обновил модель  Role добавил permission

Revision ID: 86e43abdba06
Revises: e8fa3f7b45e8
Create Date: 2026-02-02 07:47:20.413229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e43abdba06'
down_revision: Union[str, Sequence[str], None] = 'e8fa3f7b45e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean, server_default=sa.true(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


    op.execute("""Insert into permissions (name) Values ('users:read'),('users:update'),('admin:read'),('admin:update')""")
    op.execute("""Insert into role_permissions (role_id, permission_id) Select r.id, p.id From roles r, permissions p Where r.name = 'admin'""")
    op.execute("""Insert into role_permissions (role_id, permission_id) Select r.id, p.id From roles r, permissions p Where r.name = 'user' AND p.name IN ('users:read', 'users:update')""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
